""" TODO: Create a list of relevant examples.
"""

load("routine.sage")

def example1():
    """ Two l2 balls in RR^4, centered at [0,0,0,0] and [1,0,0,0].

    About this example: Challenged by Bernd to compute something in dimension 4! This creates the smallest degree non-trivial example.
    The slightly more trivial example would be the the single l2 ball in RR^4. The latter, however, one has to be careful with,
    since creative telescoping over the rational Weyl algebra will provide the wrong result, since the integrand will be decomposible as derivatives of rational functions.
    """
    n = 4
    p = 2

    S = PolynomialRing(QQ, "x", n)
    x = S.gens()

    mus = [[0,0,0,0], [1,0,0,0]]

    fs = [shifted_lp_poly(S, p, mu) for mu in mus]

    print("The shifted l{} polynomials are:".format(p))
    print(fs)

    def_var_name = "t"
    Ft = deformed_product(fs, def_var_name)
    flt_morphism = Ft.parent().flattening_morphism()
    Ft_flattened = flt_morphism(Ft) # For simplicity used later.
    
    print("\nThe deformed product:")
    print(Ft)

    print("\nNow let us compare the different derivatives:")
    for xi in x:
        print("Diff(Ft, {}) = {}".format(str(xi), diff(Ft_flattened, flt_morphism(xi))))
    
    print("\nOne observes that the derivatives in the directions {} have fewer terms.".format([str(xi) for xi in x if not xi == x[0]]))
    print("Also they symmetric, i.e. are obtained from each other by permutation of the variables.")

    strategy_var = x[1]
    print("\nAs an integral representation for the volume of the deformation w.r.t. t, we thus chose as representative of the cohomology class of the integrand:")
    print("\nAt = diff(Ft, {})*{} / Ft".format(strategy_var, strategy_var))

    At = construct_integrand_t(fs, def_var_name, prim_var_name=str(strategy_var))

    print("\nAt = {}".format(At))

    Wt = rational_weyl_algebra(At.parent().ring())

    print("\nWe consider its annihilator in the rational Weyl algebra:")
    print("\nWt = QQ({})<{}>".format(",".join([def_var_name] + [str(xi) for xi in x]), ",".join(["D" + def_var_name] + ["D" + str(xi) for xi in x])))
    print("\nMore precisely we consider the ideal generated by: ")
    print("\n[At*D - D(At) for D in Wt.gens()]")

    annAt = Wt.ideal([At*D-D(At) for D in Wt.gens()]) # construct the annihilating ideal
    
    print("\nIntegrating out all variables but t yields the Picard-Fuchs operator: ")

    # TODO: Add timing.

    intIdeal_t = creative_telescoping(annAt, At.parent().ring()(def_var_name))
    Pt = intIdeal_t.gens()[0]
    print("\nPt = {}".format(Pt))
    
    strategy_var = x[0]
    print("\nNote that we could have also considered as representative the integrand w.r.t. {}".format(strategy_var))
    print("\nIn that case the result is:")
    
    At_x0 = construct_integrand_t(fs, def_var_name, prim_var_name=str(strategy_var))
    annAt = Wt.ideal([At*D-D(At) for D in Wt.gens()]) # construct the annihilating ideal
    intIdeal_t_x0 = creative_telescoping(annAt, At.parent().ring()(def_var_name))

    Pt_x0 = intIdeal_t_x0.gens()[0]
    print("\nPt_x0 = {}".format(Pt_x0))

    print("\n[TODO] Add timining here for the two cases!")

    print("Note: Pt == Pt_x0: {}".format(Pt == Pt_x0))
    print("This to be expected at least at the theoretical level, since the annihilator of the integral doesn't depend on the choice of representative of the cohomology class.")


    print("\nAs initial data for the Picard-Fuchs operator w.r.t. t, we need to provide the volume of the deformations for different t0.")

    deform_value = QQ(0.001)
    Ft0 = eval_poly(Ft, [deform_value])

    print("The deformed product evaluated at t = {}:".format(deform_value))
    print(Ft0)

    print("Now, the deformed region we might project onto any of the {} axes.".format(",".join([str(xi) for xi in x])))
    print("Note, while the shape is symmetric with respect to the variables {}".format([str(xi) for xi in x if not xi == x[0]]))
    print("it is not additionally symmetric w.r.t. the x0 axis.")

    print("\nLet us now compare the computation of the Picard-Fuchs operator for the projection onto either the x0 or the x1 axis.")

    print("#\n# The x0 axis case:\n#")

    proj_var = x[0]
    A = construct_integrand(fs, deform_value, {}, proj_var)
    
    print("\nThe integrand:")
    print("A = {}".format(A))

    W = rational_weyl_algebra(A.parent().ring())

    annA = W.ideal([A*D-D(A) for D in W.gens()]) # construct the annihilating ideal
    
    intIdeal = creative_telescoping(annA, proj_var)

    Px0 = intIdeal.gens()[0]

    print("The Picard-Fuchs operator for the projection of the deformed intersection onto the {} axis: ".format(proj_var))
    print("\nPx0 = {}".format(Px0))

    print("[WARNING] This is bad. But the reason should be again that the slices are l2 balls in RR^4.")

    proj_var = x[1]
    print("\nIf instead we do the computation for the projection onto the {} axis, we get:".format(proj_var))
    
    A = construct_integrand(fs, deform_value, {}, proj_var)
    annA = W.ideal([A*D-D(A) for D in W.gens()]) # construct the annihilating ideal
    intIdeal = creative_telescoping(annA, proj_var)

    Px1 = intIdeal.gens()[0]
    print("\nPx1 = {}".format(Px1))

    print("\nFinally, let us carry out a volume computation for the deformed intersection, i.e. for t = {}".format(deform_value))
    # TODO: Implement strategy. I.e. as dict: strategy = {"proj_var": lambda params -> proj_var, "prim_var": lambda params -> prim_var}
    # TODO: Can also test the computation of the slice volumes w.r.t. the x0 projection. This should already work.
    #       i.e. by setting up initial value problem by hand.
    # Question / TODO: Should also see if one of the functions is decomposable as rational functions, does this hold true for the restriction?

    # TODO: Also we should verify the certificates.

    # Compute critical values and singular locus of operator.
    print("\nFor this, we are solving the differential operator Px1*dx1, i.e. thereby solving for the integral of the volume of the slice of the x1-projection.")
    print("Note that (by log-concavity, see paper) there are two relevant critical values for the x1-projection which are bounding the deformed intersection. They are:")
    
    prec = 200 # Setting number of precision bits.
    relevant_crit_val = [pt[proj_var] for pt in project_deformed_intersection(fs, deform_value, proj_var, {}, prec)]
    print(relevant_crit_val)

    assert(len(relevant_crit_val) == 2)
    min_crit_val = min(relevant_crit_val)
    max_crit_val = max(relevant_crit_val)

    print("\nWe are now sampling order(P)={} many rational {} values in this region at which we will provide the initial data for P*d{}".format(Px1.order(), proj_var, proj_var))
    print("Note that the differential operator also might have apparent singularities, i.e. roots of the leading coef which lie in our interval. Thus we restrict the range even further.")
    lead_coef = Px1.leading_coefficient().numerator()
    singular_locus = lead_coef.roots(AA, multiplicities=False) # identify_real_roots(lead_coef, prec, force_real=False) # solves in QQbar, but only takes the ones with small imaginary part.
    print("Singular locus:", singular_locus)

    # Set the interval in which we want to sample points, identify our branch points among
    # TODO: Make sure that this uniquely identifies points of the singular locus.
    xmin = singular_locus[np.argmin([np.abs(root - min_crit_val) for root in singular_locus])]
    xmax = singular_locus[np.argmin([np.abs(root - max_crit_val) for root in singular_locus])]

    CBF = ComplexBallField(prec)
    initial_points = get_good_initial_points(Px1, CBF(xmin).real(), CBF(xmax).real())
    print("Sampled points:")
    print(initial_points)

    print("\nAt each of the sampled point, we compute the volume of the slice over that value of x1:")
    slice_vols = dict((val, volume1(fs, deform_value, {x[1]:val}, prec=prec, debug_level=3)) for val in initial_points)

    print("The volumes of the slices: {}".format(slice_vols))
    # WARNING: This says that the involved system is NOT 0 dimensional! I.e. the system we get has dim 1!
    # 2026-01-09: Using hypersurface complements now.



def last_variable_proj_var_strategy(fs, deform_value, var_value_pairs):
    evaluated_poly = partial_eval_poly(eval_poly(deformed_product(fs), [deform_value]), var_value_pairs)

    return evaluated_poly.parent().gens()[-1]

def example1_reduced():

    n = 4
    p = 2

    S = PolynomialRing(QQ, "x", n)
    x = S.gens()

    mus = [[0,0,0,0], [1,0,0,0]]

    fs = [shifted_lp_poly(S, p, mu) for mu in mus]

    proj_var = x[1]

    deform_value = QQ(0.001)
    
    A = construct_integrand(fs, deform_value, {}, proj_var)
    W = rational_weyl_algebra(A.parent().ring())
    annA = W.ideal([A*D-D(A) for D in W.gens()]) # construct the annihilating ideal
    intIdeal = creative_telescoping(annA, proj_var)

    Px1 = intIdeal.gens()[0]
    print("\nPx1 = {}".format(Px1))

    
    print("\nFinally, let us carry out a volume computation for the deformed intersection, i.e. for t = {}".format(deform_value))

    # Compute critical values and singular locus of operator.
    print("\nFor this, we are solving the differential operator Px1*dx1, i.e. thereby solving for the integral of the volume of the slice of the x1-projection.")
    print("Note that (by log-concavity, see paper) there are two relevant critical values for the x1-projection which are bounding the deformed intersection. They are:")
    
    prec = 400 # Setting number of precision bits.
    relevant_crit_val = [pt[proj_var] for pt in project_deformed_intersection(fs, deform_value, proj_var, {}, prec)]
    print(relevant_crit_val)

    assert(len(relevant_crit_val) == 2)
    min_crit_val = min(relevant_crit_val)
    max_crit_val = max(relevant_crit_val)

    print("\nWe are now sampling order(P)={} many rational {} values in this region at which we will provide the initial data for P*d{}".format(Px1.order(), proj_var, proj_var))
    print("Note that the differential operator also might have apparent singularities, i.e. roots of the leading coef which lie in our interval. Thus we restrict the range even further.")
    lead_coef = Px1.leading_coefficient().numerator()
    singular_locus = lead_coef.roots(AA, multiplicities=False) # identify_real_roots(lead_coef, prec, force_real=False) # solves in QQbar, but only takes the ones with small imaginary part.
    print("Singular locus:", singular_locus)

    # Set the interval in which we want to sample points, identify our branch points among
    # TODO: Make sure that this uniquely identifies points of the singular locus.
    xmin = singular_locus[np.argmin([np.abs(root - min_crit_val) for root in singular_locus])]
    xmax = singular_locus[np.argmin([np.abs(root - max_crit_val) for root in singular_locus])]

    CBF = ComplexBallField(prec)
    initial_points = get_good_initial_points(Px1, CBF(xmin).real(), CBF(xmax).real())
    print("Sampled points:")
    print(initial_points)

    print("\nAt each of the sampled point, we compute the volume of the slice over that value of x1:")


    strategy = {"proj_var":last_variable_proj_var_strategy}

    slice_vols = dict((val, volume1(fs, deform_value, var_value_pairs={x[1]:val}, prec=prec, debug_level=3, strategy=strategy)) for val in initial_points)

    print("The volumes of the slices: {}".format(slice_vols))

    # RMK: It feels a bit weird, but the operator only has one real singular value, namely at 1/2, i.e.
    #           an apparent singularity for our example.  
    #           So the error comes from trying to sample from the len 0 interval (1/2, 1/2)  
    # [TODO]    But this would mean that the boundary values don't correspond to critical values necessarily.
    
    # [TODO]    This is a good point in time to check that the certificates are actually correct. 
    #           I.e. to carry out the process with certificates and then only print them in debug mode.

    # [TODO]    If this appears to be correct, we might have to adapt the implementation in that it additionally 
    #           provides the branch_points in QQbar so that we at least use an exact value.
    #


def exampleRR1p2k1():
    """ TODO: 
            Make completly documented example. Make sure that "debug" mode is implemented, therefore showing all all steps and 
                intermediate PF operators etc.
            Later to be printed to a file.

        RR^1. Unit ball. Centered at 0.
    """
    pass

def unit_vector_examples_p2():
    """ For p=2, consider the setting of n unit balls in unit vector position in Rn.
    For this we place the n unit balls to be centered at each of the basis vectors.

    For n=1,2,3,4. (generating polynomials of degree 2,4,6,8. Which should still be feasible.)
    """

    p = 2
    prec = 200

    for n in [1,2,3,4]:
        print("[n={}, p={}] Starting computation of RR^{} case.".format(n,p,n))
        # mus are the rows of the identity matrix
        mus = [list(mu) for mu in np.identity(n, int)]
        print("[n={}, p={}] mus = {}".format(n, p, mus))

        S = PolynomialRing(QQ, "x", n)
        x = S.gens()

        fs = [shifted_lp_poly(S, p, mu) for mu in mus]

        print("[n={}, p={}] fs = {}".format(n, p, fs))

        print("[n={}, p={}] Starting intersection volume computation with prec = {} precision bits.".format(n, p, prec))

        vol = volume2(fs, prec, strategy=None)

        # TODO: Add intermediate steps in here!

        print("[n={}, p={}] vol = {}".format(n, p, vol))

        print("[n={}, p={}] End of computation of RR^{} case.\n".format(n,p,n))


def the_positive_dim_crit_locus_example():
    """ For the example of two l2 balls shifted by 1, one notices that the critical locus of the projection (of the the deformed intersection)
    onto the x0 axis is positive dimensional.
    """
    n = 4
    p = 2

    S = PolynomialRing(QQ, "x", n)
    x = S.gens()

    mus = [[0,0,0,0], [1,0,0,0]]

    fs = [shifted_lp_poly(S, p, mu) for mu in mus]
    def_value = QQ(0.001)
    F = eval_poly(deformed_product(fs, "t"), def_value)
    
    prec = 200

    proj_var = x[0]
    print("Trying to compute the relevant critical values of the projection onto the {}-axis:".format(proj_var))
    

    relevant_crit_vals = project_deformed_intersection(fs, def_value, proj_var, {}, prec=NUM_BITS_PRECISION)
    
    print("The relevant_crit_vals: ", relevant_crit_vals)

def example_translation_RR4():
    n = 4
    p = 2

    S = PolynomialRing(QQ, "x", n)
    x = S.gens()

    mus = [[0,0,0,0], [1,0,0,0]]

    fs = [shifted_lp_poly(S, p, mu) for mu in mus]

    print("Computing the volume of the intersection of two l2 balls in RR4 centered at {}".format(mus))
    prec = 200
    strategy={"proj_var":last_variable_proj_var_strategy}
    vol = volume2(fs, prec, strategy=strategy, debug_level=3)

    print("The volume = {}".format(vol))


def example_translation_RR4_MC():
    """Verify the above with monte carlo.""" 

if __name__ == "__main__":
    #example1()
    #example1_reduced()
    #unit_vector_examples_p2()

    # the_positive_dim_crit_locus_example()

    example_translation_RR4()
    