# sys.path.insert(0, '/Users/lakshmiramesh/Desktop/ore_algebra/src')
import ore_algebra
from ore_algebra import *

# Global parameters

NUM_BITS_PRECISION = 20 # i.e. Precision of 1 / 2^NUM_BITS_PRECISION.

# TODO: Over which field are solutions computed?

# Classical assertions:
def all_from_same_parent_ring(fs):
    return all([f.parent() == fs[0].parent() for f in fs])

# Useful methods:

def eval_poly(f, var_values):
    """ Evaluates a polynomial at a specified value of the variables. 
    This method is a wrapper for applying to f the ring map to the base ring, 
    which sends the variables to the specified values.

    Input
    -------
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_values : a vector of length len(f.parent().gens()) with values in base_ring(f.parent()).
    Output
    -------
        f(var_val[0],.., var_val[-1])
    """
    phi = f.parent().hom(var_values, f.parent().base_ring())
    return phi(f)

def partial_eval_poly(f, var_value_pairs):
    """ Evaluate f at the given var value pairs. 

    Input
    -----
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_value_pairs : Dictionary with  variable:value   key-value-pairs, where value is in R.

    Output
    ----
        Geometrically restricts f to the smaller space, defined by the var_value_pairs.
        In particular, the result will lie in the polynomial ring generated by the variables not specified.
    
    Caveat
    ----
        It seems variables in sage are hashable and thus can be used as a dictionary key.
    """
    # Build an "evaluation vector" which keeps the non-specified variables in place.
    R = f.parent()
    images = [var_value_pairs[x] if x in var_value_pairs.keys() else x for x in R.gens()]

    unspecified_vars = [x for x in R.gens() if x not in var_value_pairs.keys()]

    # Define the evaluation map. Note the * operator unpacks the variables into the polynomial ring constructor.
    phi = R.hom(images, R.base_ring()[*unspecified_vars])

    return phi(f)


def shifted_lp_poly(R, p, mu):
    """ Constructs the shifted lp polynomial in the polynomial ring R. 

    Input
    ------
        R : PolynomialRing
        p : python int 
        mu : vector of size len(R.gens()) with entries in R.base_ring()  

    Caveat
    -------
        The convention we choose is that the interior of the lp ball is defined by 
        lp_poly >= 0.
    """
    return 1 - sum([(R.gens()[i] - mu[i])^(p) for i in range(0, len(R.gens()))])

def deformed_poly(f, defvarname):
    """ Introduces a new variable with the name defvarname, i.e. t, and returns f - t in the amended ring. 

    Input
    ------
        f : Polynomial 
        defvarname : string, indicating the new deformation variable

    Ouput
    ------
        f - t in the new ring f.parent()[t].
    """
    Rt = PolynomialRing(f.parent(), [defvarname])
    return f - Rt.gens()[0]
    
def deformed_product(fs, defvarname = "t"):
    """ Takes the product and deforms it by a parameter "defvarname".
    """

    # Check all are from the same parent ring.
    assert(all_from_same_parent_ring(fs))
    return deformed_poly(prod(fs), defvarname)
    

def get_1_dim_volume(fs, var_value_pairs, def_value, prec=NUM_BITS_PRECISION):
    """ In the setting of shifted lp-balls for p even, this return volume of the 
    deformed intersection of lp-balls ((Prod fs) - t) after intersection with the line defined by the 
    coordinate values for all but one coordinate.

    Input
    ------
        fs : List of polynomials in the same polynomial ring over QQ. 
        var_value_pairs : List of pairs (variable, value)
        def_value : Value, by which the product of the fs will be deformed.
        prec : Natural number, defining precision up to 2^(-prec).

    Output
    ------
        Length of the line defined by var_value_pairs intersecting with the deformed intersection of the {f >= 0}.

    Caveat:
    ------ 
        Assumes that the line actually intersects the deformed object and 
        that $t$ lies between 0 and the first critival value of the projection 
        from {(prod(fs) - t) = 0} to the t axis.

    TODO
    ------
    # TODO: Raise error when variable appears twice. 
    # TODO: Also need to make the caveat more precise.
    """
    # Deform the product to prod(fs) - t by the specified value for t.
    def_poly = eval_poly(deformed_product(fs), def_value)

    # Partially evaluate def_poly to land in a univariate polynomial ring.
    univariate_poly = partial_eval_poly(def_poly, var_value_pairs) 

    # HEURISTIC: The relevant line segment is bounded by the middle two real roots of univariate_poly,
    # see also the respective proposition in our paper. Will have evenly many roots in this setting.

    # Note: Also the real roots are only "real" with the given precision.

    real_roots = identify_real_roots(univariate_poly, prec, force_real=True)
    num_roots = len(real_roots)
    assert(num_roots % 2 == 0)

    # Sort the roots in increasing order:
    real_roots.sort()

    # The following difference will necesarily be positive.
    return real_roots[num_roots // 2] - real_roots[num_roots // 2 - 1]

def identify_real_roots(f, prec=NUM_BITS_PRECISION, force_real=False):
    """ For a univariate polynomial with rational coefficients, 
    it determines the roots which are real valued with the given precision.

    Strategy: Computes roots in QQbar. Discards roots with imaginary part larger than 2^(-prec) and 
                returns the remaining, still possibily represented to be complex valued, roots.
            
            TODO: Could also define the distance in terms of the value of f.

    Input
    ------
        f : Univariate polynomial over QQ.
        prec : precision in number of bits by which to discard imaginary parts.
        force_real : Boolean, whether the output should be forced to be algebraic real.
    """

    all_roots = f.roots(ring=QQbar)
    real_roots = [(root[0].real() if force_real else root[0])  for root in all_roots if abs(root[0].imag()) < 2^(-prec)]
    return real_roots

def branch_points(f, proj_var):
    """ Computes all the branch points, i.e. points on V(f) over CC, relative
        to the projection onto the proj_var-axis.

        The branch points are the solutions to the ideal 
            I = (f) + ( diff(f, x_i) | x_i != proj_var).
        
        The solutions are computed over CC.
    
    Input
    ------
        f : Multivariate polynomial over QQ
        proj_var : A variable out of f.parent().gens()

    Output
    ------
        A representation of the branchpoints.
    """
    pass

def project_deformed_intersection(fs, def_value, proj_var, var_value_pairs):
    """ Computes the minimum and maximum value that proj_var takes on the deformed volume_intersection,
    after restricting to the chosen var_value_pairs.

    Input
    -------
        fs : A list of multivariate polynomials

    Output
    -------
        An interval representing the [min, max] value of proj_var on the deformed intersection.
    
        This can be done in terms of computing real branch_points lieing on the boundary 
        of the deformed intersection. However, here we will use semi-definite programming.

    Caveat
    -------
        The semi-algebraic set "intersection" refers to the intersection of {f_i >= 0}.
        The "deformed semi-algebraic set" refers to the connected component of {prod(f) - t >= 0}
        that lies within the "intersection".

    """
    pass


# def volume_intersection(p, translation_vectors, precis): #assume that dim > 1, p>1 even, translation vectors give non-empty intersection!
#     """ Computes the volume of the intersection of L_p balls shifted by translation_vectors in RR^dim. 

#     Input
#     -----
#     p : integer, assumed even.
#     translation_vectors : list of vectors in QQ^dim
#     precis : integer precision digits

#     Output
#     ------
#     The volume of the intersection of the translated L_p balls as a fixed precision real number.

#     Example
#     -----
    
#     p = 4
#     translation_vectors = [(0,0), (1,0)]
    
#     vol = volume_intersection(dim,p,translation_vectors)  # 1.71448285904485523624162985240570841916093...

#     """
#     dim = len(translation_vectors[0])
#     k = len(translation_vectors)
#     Rt = PolynomialRing(ZZ, 'x', dim+1) # note that xdim+1 is t, i.e. Rt.gens()[-1] or Rt.gens()[xdim]
#     Ft = Rt.fraction_field()    
#     Wt = OreAlgebra(Ft, *[("Dx" + str(i), {}, {"x" + str(i) : 1}) for i in range(0, dim+1, 1)])
    
#     # create complex ring for creative telescoping and real ring for precision 
#     # 

#     # make the polynomial ft = f1*...*fk - t
#     ft = Rt(1)
#     for mu in translation_vectors: 
#         ft = ft * shifted_lp_poly(Rt, p, mu)

#     ft = ft - Rt.gens()[-1]

#     At = Ft(y*ft.derivative(Rt.gens()[0])/ft) # differentiat by x0. this means we always telescope wrt x0 first.  
#     annt = Wt.ideal([At*D-D(At) for D in Wt.gens()])

#     # telescope to get Picard-Fuchs in xdim+1  (i.e. eliminate all variables but the last one)
#     ct0 = annt.ct(Wt.gens()[0], certificates=False)
#     for i in range(1, dim): 
#         ct0 = ct0[0].parent().ideal(ct0).ct(Wt.gens()[i], certificates=False)
#     order0 = ct0[0].order()

#     # CHOOSE SLICES 
#     max0 = QQ[Rt.gens()[dim+1]](ct0[0].leading_coefficient()).roots(RB, multiplicities=False) #what is RB
#     # TODO : Find the t0 smallest positive, real critical value and choose order0 many points between 0 and  t0
#     # L0 = [...] values of x0 for slices! 
#     # Check if L0 is a good set - it should give an invertible matrix. before or after computing volumes? 

#     # now we compute order0 volumes of x[dim]-slices. 
#     x0_volumes = []
#     for i in range(0,order0):
#         # smooth algorithm begins here
#         j=0
#         # f = ft(R.gens()[dim] = L[i]) #evaluate it before calling!!
#         something = smooth_volume(j,L[i],ft,dim,RB)
#         x0_volumes.append(something)
#     # analytically continue to get volume at x[dim] = 0
#     return final_volume


# def smooth_volume(j, point, f1, dim, RB):
#     R = PolynomialRing(ZZ, dim-j, 'x') #Note that now, x0 = x, x1 = y, ...
#     F = R.fraction_field()    
#     W = OreAlgebra(F, *[("Dx" + str(i), {}, {"x" + str(i) : 1}) for i in range(0, dim-j, 1)])
#     # TODO
#     # f = None
#     f = F(f1(R.gens()[dim - j] = QQ(point))) #can't evaluate here!!
#     A = F(y*f.derivative(R.gens()[0])/f)
#     ann = W.ideal([A*D-D(A) for D in W.gens()])
#     ct = ann.ct(W.gens()[0], certificates=False)
#     if j == dim-2:
#         # do nothing
#         pass
#     else:
#         for k in range(1,dim-j-1):
#             ct = ct[0].parent().ideal(ct).ct(W.gens()[k], certificates=False)
#     ord = ct[0].order()
#     L = QQ[R.gens()[dim-j-1]](ct[0].leading_coefficient()).roots(RB, multiplicities=False)
#     # TODO kick out unwanted critical points
#     initial_conditions = []
#     slice_values = #find ord+1 slices
#     for i in ord+1:
#         if j == dim-2: 
#             # TODO actually compute a volume 
#             # here we must use our conjecture.
#             f = f(R.gens()[dim - j] = slice_values[i])
#             # we select the middle two points
#             roots = (QQ[R.gens()[0]](f)).roots(RB, multiplicities=False)
#             len_roots = len(roots) + 1 # this should be even
#             slice_vol = roots[len_roots/2] - roots[len_roots/2 - 1]
#         else:
#             slice_vol = smooth_volume(j+1, slice_values[i], f, dim, RB)
#             initial_conditions.append(slice_vol)

#     # TODO use the initial conditions to compute the volume of this slice. 
#     return volume        
    