# sys.path.insert(0, '/Users/lakshmiramesh/Desktop/ore_algebra/src')

# Insert also the link to the msolve interface:
load("sage2msolve.sage")

import ore_algebra
from ore_algebra import *

from scipy import optimize
import numpy as np

# Custom exceptions:

class BadPointsError(Exception):
    pass


# Global parameters

NUM_BITS_PRECISION = 20 # i.e. Precision of 1 / 2^NUM_BITS_PRECISION.

# TODO: Over which field are solutions computed?

# Classical assertions:
def all_from_same_parent_ring(fs):
    return all([f.parent() == fs[0].parent() for f in fs])

# Useful methods:

def eval_poly(f, var_values):
    """ Evaluates a polynomial at a specified value of the variables. 
    This method is a wrapper for applying to f the ring map to the base ring, 
    which sends the variables to the specified values.

    Input
    -------
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_values : a vector of length len(f.parent().gens()) with values in base_ring(f.parent()).
    Output
    -------
        f(var_val[0],.., var_val[-1])
    """
    phi = f.parent().hom(var_values, f.parent().base_ring())
    return phi(f)

def partial_eval_poly(f, var_value_pairs, infer_target_base_ring=False):
    """ Evaluate f at the given var value pairs. 

    Input
    -----
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_value_pairs : Dictionary with  variable:value   key-value-pairs, where value is in R.

    Output
    ----
        Geometrically restricts f to the smaller space, defined by the var_value_pairs.
        In particular, the result will lie in the polynomial ring generated by the variables not specified.
    
    Caveat
    ----
        It seems variables in sage are hashable and thus can be used as a dictionary key.

    TODO
    ----
        Infer the target ring type from the var_value_pairs. Else might fail, if first variable value is not specified.
    """
    # Build an "evaluation vector" which keeps the non-specified variables in place.
    R = f.parent()
    images = [var_value_pairs[x] if x in var_value_pairs.keys() else x for x in R.gens()]
    assert(len(images) >= 0)

    unspecified_vars = [x for x in R.gens() if x not in var_value_pairs.keys()]

    # Define the evaluation map. Note the * operator unpacks the variables into the polynomial ring constructor.
    # TODO: The target base_ring has to be infered from the var_value pairs!!
    target_base_ring = images[0].base_ring() if infer_target_base_ring else R.base_ring()
    phi = R.hom(images, target_base_ring if len(unspecified_vars) == 0 else target_base_ring[*unspecified_vars])

    return phi(f)


def shifted_lp_poly(R, p, mu):
    """ Constructs the shifted lp polynomial in the polynomial ring R. 

    Input
    ------
        R : PolynomialRing
        p : python int 
        mu : vector of size len(R.gens()) with entries in R.base_ring()  

    Caveat
    -------
        The convention we choose is that the interior of the lp ball is defined by 
        lp_poly >= 0.
    """
    return 1 - sum([(R.gens()[i] - mu[i])^(p) for i in range(0, len(R.gens()))])

def deformed_poly(f, defvarname):
    """ Introduces a new variable with the name defvarname, i.e. t, and returns f - t in the amended ring. 

    Input
    ------
        f : Polynomial 
        defvarname : string, indicating the new deformation variable

    Ouput
    ------
        f - t in the new ring f.parent()[t].
    """
    Rt = PolynomialRing(f.parent(), [defvarname])
    return f - Rt.gens()[0]
    
def deformed_product(fs, defvarname = "t"):
    """ Takes the product and deforms it by a parameter "defvarname".
    """

    # Check all are from the same parent ring.
    assert(all_from_same_parent_ring(fs))
    return deformed_poly(prod(fs), defvarname)
    

def get_1_dim_volume(fs, var_value_pairs, def_value, prec=NUM_BITS_PRECISION):
    """ In the setting of shifted lp-balls for p even, this return volume of the 
    deformed intersection of lp-balls ((Prod fs) - t) after intersection with the line defined by the 
    coordinate values for all but one coordinate.

    Input
    ------
        fs : List of polynomials in the same polynomial ring over QQ. 
        var_value_pairs : List of pairs (variable, value)
        def_value : Value, by which the product of the fs will be deformed.
        prec : Natural number, defining precision up to 2^(-prec).

    Output
    ------
        Length of the line defined by var_value_pairs intersecting with the deformed intersection of the {f >= 0}.

    Caveat:
    ------ 
        Assumes that the line actually intersects the deformed object and 
        that $t$ lies between 0 and the first critival value of the projection 
        from {(prod(fs) - t) = 0} to the t axis.

    TODO
    ------
    # TODO: Raise error when variable appears twice. 
    # TODO: Also need to make the caveat more precise.

    [TODO] Rephrase both in terms of convexity, vs. just the two points within all the other {f > 0} for f in fs.
            and then check that there are only two in the intersection.
    """
    # Deform the product to prod(fs) - t by the specified value for t.
    def_poly = eval_poly(deformed_product(fs), def_value)

    # Partially evaluate def_poly to land in a univariate polynomial ring.
    univariate_poly = partial_eval_poly(def_poly, var_value_pairs) 
    var_name = univariate_poly.parent().gens()[0]

    # HEURISTIC: The relevant line segment is bounded by the middle two real roots of univariate_poly,
    # see also the respective proposition in our paper. Will have evenly many roots in this setting.

    # Note: Also the real roots are only "real" with the given precision.

    real_variety = variety_msolve([univariate_poly], prec) # identify_real_roots(univariate_poly, prec, force_real=True)
    num_roots = len(real_variety)
    assert(num_roots % 2 == 0)

    # print("Real variety: {}".format(real_variety))

    # Sort the roots in increasing order:
    real_values = [pt[var_name] for pt in real_variety]
    real_values.sort()
    # print("Real values: {}".format(real_values))

    # The following difference will necesarily be positive.
    return real_values[num_roots // 2] - real_values[num_roots // 2 - 1]


# TODO: Below function is obsolete.
# TODO: Instead of the below, simply use msolve! It does real root isolation.
def identify_real_roots(f, prec=NUM_BITS_PRECISION, force_real=False):
    """ For a univariate polynomial with rational coefficients, 
    it determines the roots which are real valued with the given precision.

    Strategy: Computes roots in QQbar. Discards roots with imaginary part larger than 2^(-prec) and 
                returns the remaining, still possibily represented to be complex valued, roots.
            
            TODO: Could also define the distance in terms of the value of f.

    Input
    ------
        f : Univariate polynomial over QQ.
        prec : precision in number of bits by which to discard imaginary parts.
        force_real : Boolean, whether the output should be forced to be algebraic real.
    """

    all_roots = f.roots(ring=QQbar)
    real_roots = [(root[0].real() if force_real else root[0])  for root in all_roots if abs(root[0].imag()) < 2^(-prec)]
    return real_roots

def get_inside_branch_points(fs, def_value, proj_var, var_value_pairs, prec=NUM_BITS_PRECISION):
    """ Return the branch points of prod(fs)-t, evaluated at def_value and var_value_pairs, that lie
    inside {f > 0} for all f in fs.

    Input
    ------
        fs              : A list of multivariate polynomials
        def_value       : In QQ, value by which the product is deformed.
        proj_var        : The variable, such that we project onto the proj_var-axis.
        var_value_pairs : The values already restricted to.
    
    Output
    ------
        inside_branch_points : List of points of the form {xi:valxi ... for all i}, where i 
                                goes over these variables that remain after the value substitutions.

    Remark
    ------
        The resulting computed branchpoints are those that lie on boundary of the smooth deformation of the intersection.
    """
    assert(def_value > 0) # The branch points would satisfy f==0 for some of the f in fs, and hence this case is not allowed.

    # Deform and compute branch points of the projection.
    fdef = partial_eval_poly(eval_poly(deformed_product(fs), [def_value]), var_value_pairs) 
    bpoints = branch_points(fdef, proj_var, prec) 
    
    # Now identify the branchpoints satisfying f > 0 for all f in fs:
    inside_branch_points = [point for point in bpoints if all([partial_eval_poly(f, point, infer_target_base_ring = True) > 0 for f in fs ])]
    
    return inside_branch_points

def branch_points(f, proj_var, prec=NUM_BITS_PRECISION):
    """ Computes all the real branch points, i.e. points on V(f) relative
        to the projection onto the proj_var-axis.

        The branch points are the solutions to the ideal 
            I = (f) + ( diff(f, x_i) | x_i != proj_var).
        
        The solutions are computed using groebner bases and real root isolation in msolve.
    
    Input
    ------
        f : Multivariate polynomial over QQ
        proj_var : A variable out of f.parent().gens()

    Output
    ------
        A representation of the branchpoints.
    """
    R = f.parent()

    # branch point system.
    system = [f] + [diff(f, x) for x in R.gens() if not (x == proj_var)]

    # Now solve the ideal, assuming it is just a collection of points.
    # TODO: Can essentially remove the the assertion, as it will be necessarily true. Why?
    assert(R.ideal(system).dimension() == 0)

    variety = variety_msolve(system, prec)

    return variety

def project_deformed_intersection(fs, def_value, proj_var, var_value_pairs, prec=NUM_BITS_PRECISION):
    """ Computes the minimum and maximum value that proj_var takes on the deformed volume_intersection,
    after restricting to the chosen var_value_pairs.

    Input
    -------
        fs              : A list of multivariate polynomials
        def_value       : In QQ, value by which the product is deformed.
        proj_var        : The variable, such that we project onto the proj_var-axis.
        var_value_pairs : The values already restricted to.

    Output
    -------
        An interval representing the [min, max] value of proj_var on the deformed intersection.
    
        This can be done in terms of computing real branch_points lying on the boundary 
        of the deformed intersection and then projecting onto proj_var.

    Caveat
    -------
        The semi-algebraic set "intersection" refers to the intersection of {f_i >= 0}.
        The "deformed semi-algebraic set" refers to the connected component of {prod(f) - t >= 0}
        that lies within the "intersection".

    """
    # If only 1 lp ball, then no need to deform!
    if def_value == 0:
        # If not deformed, only 1 poly (smooth bdry!) supported
        assert(len(fs) == 1)
        return [{proj_var:point[proj_var]} for point in branch_points(fs[0], proj_var, prec)]    

    # Now identify the branchpoints satisfying f >= 0 for all f in fs:
    inside_branch_points = get_inside_branch_points(fs, def_value, proj_var, var_value_pairs, prec)
    
    # Now return only the proj_var values 
    return [{proj_var:point[proj_var]} for point in inside_branch_points]


def get_picard_fuchs(fs, deform_value, var_value_pairs, proj_var, strategy=None):
    """ Computes the Picard Fuchs operator for 
    Vol(proj_var) = Vol( p^{-1}(proj_var) \cap {fs \geq 0 forall s} \cap slice(var_value_pairs)).

    Input
    ------
    fs              : Polynomials defining semi-alg set (by fs >= 0)
    deform_value    : Value in QQ, by which to smooth prod(fs).
    var_value_pairs : defining slice to restrict to.

    Output
    ------
    P : Picard Fuchs operator, in WeylAlgebra D_{proj_var}

    TODO
    -----
    Make the procedure by which to compute the intersection ideal more informed.
    """

    # Construct the integrand
    A = construct_integrand(fs, deform_value, var_value_pairs, proj_var)
    
    W = rational_weyl_algebra(A.parent().ring())

    annA = W.ideal([A*D-D(A) for D in W.gens()]) # construct the annihilating ideal

    # To be precise, below we simply construct some subset of the integration ideal, 
    # but it suffices to be non-empty.
    intIdeal = creative_telescoping(annA, proj_var)

    return intIdeal.gens()[0]

def construct_integrand(fs, deform_value, var_value_pairs, proj_var):
    """ By standard considerations, see for example our paper, the function 
    vol(proj_var) can be expressed as period of a rational function A. 
    We construct this function rational function here, considering  closely the order of indeterminate variables
    and the proj var.

    Input
    ------
    See get_picard_fuchs()

    Output
    -----
    A : Element of a FractionField. (TODO: Specify more clearly the variables.)
    """

 
    fdef = partial_eval_poly(eval_poly(deformed_product(fs), [deform_value]), var_value_pairs)
    
    # Multiply out the denominators and change to integer ring:
    fdef_ZZ = fdef.numerator().change_ring(ZZ)
    proj_var_ZZ = fdef_ZZ.parent()(proj_var)

    prim_var = [var for var in fdef_ZZ.parent().gens() if not var == proj_var_ZZ][0] # TODO: Here taking the first, should make this more strategic here.
    
    sgn = (-1)^0 # TODO: Should depend on the choice of prim_var, to account for ordering.

    A = sgn * diff(fdef_ZZ, prim_var) * prim_var / fdef_ZZ # Automatically constructs the fraction field.

    return A


def get_picard_fuchs_t(fs, strategy=None):
    """ Computes the Picard Fuchs operator for 
    Vol(t) = Vol( prod(fs) - t >= 0) \cap {fs \geq 0 forall s} 

    Input
    ------
    fs              : Polynomials defining semi-alg set (by fs >= 0)

    Output
    ------
    P : Picard Fuchs operator, in WeylAlgebra D_{t}

    TODO
    -----
    Make the procedure by which to compute the intersection ideal more informed.
    """

    deform_var_name = "t"

    # Construct the integrand, note that here this is over the ring QQ[x..., t], rather than QQ[x..][t]
    At = construct_integrand_t(fs, deform_var_name, strategy)
    
    Wt = rational_weyl_algebra(At.parent().ring())

    annAt = Wt.ideal([At*D-D(At) for D in Wt.gens()]) # construct the annihilating ideal

    # To be precise, below we simply construct some subset of the integration ideal, 
    # but it suffices to be non-empty.
    intIdeal_t = creative_telescoping(annAt, At.parent().ring()(deform_var_name))

    return intIdeal_t.gens()[0]


def construct_integrand_t(fs, def_var_name, strategy=None):
    """ See construct_integrand(). Constructs the picard fuchs operator for the deformed slice
    vol(t) = vol({prod(fs)-t >= 0} \cap {fs >= 0})

    Input
    -----
        See get_picard_fuchs_t()
    """

    ft = deformed_product(fs, def_var_name)

    ft_flattened = ft.parent().flattening_morphism()(ft) # flatten the ring.

    # Multiply out the denominators and change to integer ring:
    ft_flattened_ZZ = ft_flattened.numerator().change_ring(ZZ)


    proj_var_ZZ = ft_flattened_ZZ.parent()(def_var_name)

    prim_var = [var for var in ft_flattened_ZZ.parent().gens() if not var == proj_var_ZZ][0] # TODO: Here taking the first, should make this more strategic here.
    
    sgn = (-1)^0 # TODO: Should depend on the choice of prim_var, to account for ordering. (Or maybe it doesn't matter? Either does annihilate it.)

    At = sgn * diff(ft_flattened_ZZ, prim_var) * prim_var / ft_flattened_ZZ # Automatically constructs the fraction field.

    return At

def rational_weyl_algebra(polyRing):
    """ Constructs the rational Weyl algebra for a specified polynomial ring.
    """
    fracField = polyRing.fraction_field()

    return OreAlgebra(fracField, *[("D" + str(var), {}, {str(var) : 1}) for var in polyRing.gens()])

def creative_telescoping(I, proj_var, strategy=None):
    """ For an ideal in the rational Weyl algebra W, it carries out creative telescoping
    sequentially to eliminate all but proj_var.

    The result is an ideal contained in:     (I + dx_1 * D + ...+ dx_n *D) \cap D_x0
    (In this example we assume x0 to be the proj_var)

    Output
    ------
    ct_ : Returns a list of of univariate differential operators of length 1 (!).

    TODO
    ------
    - Should extend this, so that at least temporarily we store / output for debuginfo the certificates, too.
    - Should include some basic strategy.
    """
    W = I.ring()
    ct_system = list(I.gens())
    for Dvar in [Dvar for Dvar in W.gens() if not Dvar == W("D"+str(proj_var))]:
        ct_ideal = ct_system[0].parent().ideal(ct_system)
        ct_system = ct_ideal.ct(Dvar, certificates=False)
    return ct_system[0].parent().ideal(ct_system)

def solve_diff_op(P, initial_conditions, evaluation_condition, prec, apparent_singular_points=[]):
    """ Given a linear differential operator in 1 variable, i.e. an ODE, solve it given the provided initial conditions
    and output the value of the solution at the requested point.

    The initial conditions specify the coefficients to the local series solutions, given the exponents of the starting monomials.
    In our case, since our solutions are bounded in the specified range, there will be no log part in the starting monomials.

    The initial condition solver is used in two scenarios:
    - Vol1:
        - Here the operator to be considered is P*dx, i.e. we solve for the value of the integral \int_a^x vol(x0)dx0.
        - At a, the corresponding starting monomial is 1 with value 0. (RMK. "a" will be a branchvalue, i.e. a singular point of the operator!)
        - At the other points the initial data is the volume of the slice at a given value of x. Thus, the corresponding starting monomial is (x-x_0)^1. 
        - The evaluation point will be the next branch_value, i.e. again a singular point of the picard fuchs operator.
    - Vol2: 
        - Directly solve the picard fuchs operator in t, i.e. for the slices of the deformed intersection and then analytically continue to t=0.
        - The initial conditions all are taken at smooth points, smaller than the first branch-value of the projection onto t. 
        - The corresponding starting monomials will always be (t-t_0)^0 = 1.


    Input
    ------
    P : Element of Weyl algebra over polynomial or rational function ring in 1 variable.
    initial_conditions : { x_val_1:{"exponent":expon, "coef":coef }, x_val_2:...}
    evaluation_condition : Dictionary containing evaluation point and the exponent 
                            of the starting monomial, whose coef shall be read of, e.g. {"pt":0, "exponent":0}

    Example
    -------
    initial_condition = {1/10:{"exponent":1, "coef":3.12223532...}, }

    Caveat
    ------
    - [TODO] Since we really depend on the order of the initial conditions to be always the same, we should store them as a list.
    - [TODO] Consider the singular points of the differential operator.
    - This is still buggy in general.
    - [TODO] Need proof that this will work in our considered scenarios.
    - [TODO] Need to check that the initial conditions are good (and can do this before evaluating I think! So we don't waste the computations of the slice volumes.)

    """
    # Assert that univariate differential operator
    assert(len(P.parent().gens()) == 1 and len(P.parent().base_ring().gens()) == 1)

    # Extract the variable:
    t = P.parent().base_ring().gens()[0]

    # Assert that the starting monomials corresponding to the exponents do exist in the standard monomials
    assert(all([(t-pt)^condition["exponent"] in P.local_basis_monomials(pt) for pt,condition in initial_conditions.items()]))

    # Assert that we provide as many initial conditions as the order of the operator
    assert(P.order() == len(initial_conditions.keys()))

    # Set up the linear system of rk = P.order() 

    # Choose a base point for the linear system, e.g. the evaluation point
    eval_point = evaluation_condition["pt"]
    # Set up some symbolic variables
    a = SR.var("a", P.order())
    # coef_vector:
    ini_eval_point = list(a) # [a0, a1,..., a{rk-1}]

    # Transition to the other points and yields linear equations in the a's.
    # More precisely: Given the unkown coefs "a" at the base point, yields an affine linear expression in "a"
    #   for the coef of the std_monomial provided in the initial data.
    lin_eqs = [(P.numerical_transition_matrix([eval_point] + [xi for xi in reversed(sorted(apparent_singular_points))] + [pt], eps=2^(-prec))*vector(ini_eval_point))[P.local_basis_monomials(pt).index((t-pt)^condition["exponent"])] for pt,condition in initial_conditions.items()]; 

    # Extract the constant terms in the affine linear equations.
    constant_terms = vector([lin_eq.subs({ai:0 for ai in a}) for lin_eq in lin_eqs])

    # Express in terms of a matrix:
    M = matrix([[lin_eq.coefficient(ai) for ai in a ] for lin_eq in lin_eqs])
    
    # Change field to complex ball field to take inverse
    CB = ComplexBallField(prec)

    # Check that determinant is non-zero (i.e. the complex ball of the determinant doesn't contain 0.)
    if not (M.change_ring(CB).determinant() != 0):
        raise BadPointsError("Determinant of the system cannot be distinguished from zero.")

    # Set up the initial data as a vector
    initial_data_vector = vector([condition["coef"] for pt,condition in initial_conditions.items()]).change_ring(CB)

    # Solve
    eval_point_coefs = M.change_ring(CB).inverse() * (initial_data_vector - constant_terms)

    # Read of the coefficient that we wanted to evaluate at:
    return eval_point_coefs[P.local_basis_monomials(eval_point).index((t-eval_point)^evaluation_condition["exponent"])]

def volume1(fs, deform_value, var_value_pairs, prec=NUM_BITS_PRECISION, strategy=None):
    """ Computes the smooth volume of the deformed intersection of lp balls. 

    Input
    -----
    fs : list of multivariate polynomials over QQ
    def_value : non-negative element in QQ
    var_value_pairs : Dictionary with  variable:value   key-value-pairs, where value is in QQ.

    Output
    ------
    The volume of the deformation of the intersection of all {f>=0 | f in fs}
    to prod(fs)-def_value. In both case only the points in the slice specified by var_value_pairs are considered.

    Caveat
    ------
    The output will be a number in the complex ball field with prec many bits of precision.



    [TODO] Add tests to test-suite.
    [TODO] Add assertions.
    [TODO] Implement good initial conditions.
    [TODO] Check if branch_points computation also works to t=0 case (so that don't need separate case.)

    [TODO] Make the choice of a projection variable strategic.

    [TODO] Assert that there is actually only a unique root in the singular locus corresponding to either numerical branch_point.

    """
    # The evaluated polynomial (for reference)
    evaluated_poly = partial_eval_poly(eval_poly(deformed_product(fs), [deform_value]), var_value_pairs)
    #print(evaluated_poly)

    # Early exit if already univariate, then return 1-dim volume.
    if len(evaluated_poly.parent().gens()) == 1:
        # print("Entering the 1 dim case for:", var_value_pairs, deform_value )
        return get_1_dim_volume(fs, var_value_pairs, deform_value, prec)

    # Fix a projection variable (here just the first undetermined variable): 
    proj_var = evaluated_poly.parent().gens()[0]

    # Get the Picard-Fuchs operator and define the operator to be solved.
    P = get_picard_fuchs(fs, deform_value, var_value_pairs, proj_var, strategy)
    Pdx = P * P.parent().gens()[0]
    # print("Order Pdx:", Pdx.order())

    # Determine the branch points and corresponding critical values bounding the deformed set.
    
    # Numerical critical values:
    relevant_crit_val = [pt[proj_var] for pt in project_deformed_intersection(fs, deform_value, proj_var, var_value_pairs, prec)]
    # print("Relevant crit cal", relevant_crit_val)

    assert(len(relevant_crit_val) == 2)
    min_crit_val = min(relevant_crit_val)
    max_crit_val = max(relevant_crit_val)

    # The singular locus in AA!!|| (exactly computed in QQbar - but need to identify reals) (from lead coef, casted to polynomial ring!)
    lead_coef = P.leading_coefficient().numerator()
    singular_locus = lead_coef.roots(AA, multiplicities=False) # identify_real_roots(lead_coef, prec, force_real=False) # solves in QQbar, but only takes the ones with small imaginary part.
    # print("Singular locus:", singular_locus)

    # Set the interval in which we want to sample points, identify our branch points among
    xmin = singular_locus[np.argmin([np.abs(root - min_crit_val) for root in singular_locus])]
    xmax = singular_locus[np.argmin([np.abs(root - max_crit_val) for root in singular_locus])]

    # apparent singularities (that are not singularities of our solution:)
    xapparent = sorted([xi for xi in singular_locus if not xi in [xmin, xmax] and (xmin < xi) and (xi < xmax)])

    # print("Xmin = ", xmin)
    # print("xmax = ", xmax)

    # print("Apparent Singular points = ", xapparent)

    # Determine points for initial data, such that transition matrix becomes invertible.
    CBF = ComplexBallField(prec)
    initial_points = get_good_initial_points(P, CBF(xmin).real(), CBF(xmax).real())
    # print("initial points:", initial_points)

    # Determine initial conditions (TODO: in parallel)
    #{"pt":0, "exponent":0} { x_val_1:{"exponent":mon, "coef":coef }, x_val_2:...}
    initial_conditions = {xmin:{"exponent":0, "coef":0}} | {xi:{"exponent":1, "coef":volume1(fs, deform_value, var_value_pairs | {proj_var:xi}, prec, strategy)} for xi in initial_points}

    # print("Initial conditions", initial_conditions)
    # print([(key.parent(), value["coef"].parent()) for key,value in initial_conditions.items()])

    evaluation_condition = {"pt":xmax, "exponent":0}

    # Solve the initial value problem
    volume = solve_diff_op(Pdx, initial_conditions, evaluation_condition, prec, xapparent)

    # Return the volume
    return volume

def get_good_initial_points(P, x0, x1):
    """ Provides n rational points strictly between x0 and x1, 
    where n is the order of the ordinary differential operator to be solved.

    Input
    -----
    [TODO]

    Output
    ------
    [TODO]

    Remark
    ------
    [TODO] Actually provide the invertibility check of the initial points.
    """
    n = P.order()
    q = sample_n_rational_points(x0,x1,n)

    # TODO: Actually check invertibility of the linear system.
    # Rmk: Note that with probability 1, the system is invertible. Ideally this check while solving the differential operator
    #   and then raising an error.

    return q


def sample_n_rational_points(x0,x1,n, base=10):
    """ Linearly samples n rational points strictly between x0 and x1.
    Determines q_start and delta, accordingly, so that

    qk = qstart + k*delta (for k = 0,..., n-1)

    yields n rational points between x0 and x1.

    In case x0 and x1 are given as algebraic numbers, it first truncates the imaginary pary.

    Determines a suitable interval in base 10.

    Remark
    ------
    [TODO] - Print delta on demand. 
    [TODO] - Which log function is this? Is it accurate?
    """
    xmax = max(x0,x1).real()
    xmin = min(x0,x1).real()

    # Determine integer N, such that 10^N < xmax-xmin 
    N = np.floor(log(xmax-xmin)/log(base))

    # Choose qstart in 2*10^(N-1) neigborhood of xmin
    qstart = QQ((np.floor(xmin / 10^(N-1)) + 2) * 10^(N-1))

    # Generate the samples linearly
    if n == 1:
        return [qstart]

    # n != 1:
    delta = QQ(10^(N-1) / (n-1))
    q = [qstart + k*delta for k in range(0,n)]

    return q


def volume2(fs, prec, strategy=None):
    """ Computes the volume of the intersection of the lp balls bigcap {f >= 0 } for f in fs.

    Input
    -----
        fs : List of polynomials over QQ describing the shifted lp balls.
        prec : Number of bits precision of the computation.

    Output
    ------
    [TODO]

    Remark
    ------
    [TODO] Change input actually to the points. This is what people will be using

    """
    # Early exit, if only 1 function:
    if len(fs) == 1:
        return volume1(fs,0, {}, prec, strategy)

    # TODO: Assertions
    assert(all_from_same_parent_ring(fs))

    # Get Picard Fuchs
    Pt = get_picard_fuchs_t(fs, strategy)

    # Choose initial points between 0 and the smallest singular point larger than 0.
    lead_coef = Pt.leading_coefficient().numerator()
    singular_locus = lead_coef.roots(AA, multiplicities=False)

    assert(0 in singular_locus)
    index_zero = sorted(singular_locus).index(0)
    
    smallest_positive_singular_point = sorted(singular_locus)[index_zero + 1] if index_zero + 1 < len(singular_locus) else QQ(1/10)

    CBF = ComplexBallField(prec)
    initial_points = get_good_initial_points(Pt, 0, CBF(smallest_positive_singular_point).real())

    # Compute initial conditions (volumes of the t slices)
    initial_conditions = {ti:{"exponent":0, "coef":volume1(fs, ti, {}, prec, strategy)} for ti in initial_points}

    # Set evaluation condition at 0
    evaluation_condition = {"pt":0, "exponent":0}

    # Solve the initial value problem
    volume = solve_diff_op(Pt, initial_conditions, evaluation_condition, prec, [])
    
    return volume



    # TODO: Current issue: Throws the error we also had a while back, when it was complaining about "Macsyma"
    # Back then we had to just change back to QQbar and then it worked again. Make sure to make analogous to the notebook computation and check the values.

    # TODO: Also might simply collect the values one gets and then simply step through the reconstruction process. Check invertibility etc..
    # TODO: Check again, if it simply works if the intersection of 2 polies slightly deformed. Then will have to add the path for analytic continuation!







# def volume_intersection(p, translation_vectors, precis): #assume that dim > 1, p>1 even, translation vectors give non-empty intersection!
#     """ Computes the volume of the intersection of L_p balls shifted by translation_vectors in RR^dim. 

#     Input
#     -----
#     p : integer, assumed even.
#     translation_vectors : list of vectors in QQ^dim
#     precis : integer precision digits

#     Output
#     ------
#     The volume of the intersection of the translated L_p balls as a fixed precision real number.

#     Example
#     -----
    
#     p = 4
#     translation_vectors = [(0,0), (1,0)]
    
#     vol = volume_intersection(dim,p,translation_vectors)  # 1.71448285904485523624162985240570841916093...

#     """
#     dim = len(translation_vectors[0])
#     k = len(translation_vectors)
#     Rt = PolynomialRing(ZZ, 'x', dim+1) # note that xdim+1 is t, i.e. Rt.gens()[-1] or Rt.gens()[xdim]
#     Ft = Rt.fraction_field()    
#     Wt = OreAlgebra(Ft, *[("Dx" + str(i), {}, {"x" + str(i) : 1}) for i in range(0, dim+1, 1)])
    
#     # create complex ring for creative telescoping and real ring for precision 
#     # 

#     # make the polynomial ft = f1*...*fk - t
#     ft = Rt(1)
#     for mu in translation_vectors: 
#         ft = ft * shifted_lp_poly(Rt, p, mu)

#     ft = ft - Rt.gens()[-1]

#     At = Ft(y*ft.derivative(Rt.gens()[0])/ft) # differentiat by x0. this means we always telescope wrt x0 first.  
#     annt = Wt.ideal([At*D-D(At) for D in Wt.gens()])

#     # telescope to get Picard-Fuchs in xdim+1  (i.e. eliminate all variables but the last one)
#     ct0 = annt.ct(Wt.gens()[0], certificates=False)
#     for i in range(1, dim): 
#         ct0 = ct0[0].parent().ideal(ct0).ct(Wt.gens()[i], certificates=False)
#     order0 = ct0[0].order()

#     # CHOOSE SLICES 
#     max0 = QQ[Rt.gens()[dim+1]](ct0[0].leading_coefficient()).roots(RB, multiplicities=False) #what is RB
#     # TODO : Find the t0 smallest positive, real critical value and choose order0 many points between 0 and  t0
#     # L0 = [...] values of x0 for slices! 
#     # Check if L0 is a good set - it should give an invertible matrix. before or after computing volumes? 

#     # now we compute order0 volumes of x[dim]-slices. 
#     x0_volumes = []
#     for i in range(0,order0):
#         # smooth algorithm begins here
#         j=0
#         # f = ft(R.gens()[dim] = L[i]) #evaluate it before calling!!
#         something = smooth_volume(j,L[i],ft,dim,RB)
#         x0_volumes.append(something)
#     # analytically continue to get volume at x[dim] = 0
#     return final_volume


# def smooth_volume(j, point, f1, dim, RB):
#     R = PolynomialRing(ZZ, dim-j, 'x') #Note that now, x0 = x, x1 = y, ...
#     F = R.fraction_field()    
#     W = OreAlgebra(F, *[("Dx" + str(i), {}, {"x" + str(i) : 1}) for i in range(0, dim-j, 1)])
#     # TODO
#     # f = None
#     f = F(f1(R.gens()[dim - j] = QQ(point))) #can't evaluate here!!
#     A = F(y*f.derivative(R.gens()[0])/f)
#     ann = W.ideal([A*D-D(A) for D in W.gens()])
#     ct = ann.ct(W.gens()[0], certificates=False)
#     if j == dim-2:
#         # do nothing
#         pass
#     else:
#         for k in range(1,dim-j-1):
#             ct = ct[0].parent().ideal(ct).ct(W.gens()[k], certificates=False)
#     ord = ct[0].order()
#     L = QQ[R.gens()[dim-j-1]](ct[0].leading_coefficient()).roots(RB, multiplicities=False)
#     # TODO kick out unwanted critical points
#     initial_conditions = []
#     slice_values = #find ord+1 slices
#     for i in ord+1:
#         if j == dim-2: 
#             # TODO actually compute a volume 
#             # here we must use our conjecture.
#             f = f(R.gens()[dim - j] = slice_values[i])
#             # we select the middle two points
#             roots = (QQ[R.gens()[0]](f)).roots(RB, multiplicities=False)
#             len_roots = len(roots) + 1 # this should be even
#             slice_vol = roots[len_roots/2] - roots[len_roots/2 - 1]
#         else:
#             slice_vol = smooth_volume(j+1, slice_values[i], f, dim, RB)
#             initial_conditions.append(slice_vol)

#     # TODO use the initial conditions to compute the volume of this slice. 
#     return volume        
    