# sys.path.insert(0, '/Users/lakshmiramesh/Desktop/ore_algebra/src')

# Insert also the link to the msolve interface:
load("../../msolvetest/sage2msolve.sage")

import ore_algebra
from ore_algebra import *

from scipy import optimize


# Global parameters

NUM_BITS_PRECISION = 20 # i.e. Precision of 1 / 2^NUM_BITS_PRECISION.

# TODO: Over which field are solutions computed?

# Classical assertions:
def all_from_same_parent_ring(fs):
    return all([f.parent() == fs[0].parent() for f in fs])

# Useful methods:

def eval_poly(f, var_values):
    """ Evaluates a polynomial at a specified value of the variables. 
    This method is a wrapper for applying to f the ring map to the base ring, 
    which sends the variables to the specified values.

    Input
    -------
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_values : a vector of length len(f.parent().gens()) with values in base_ring(f.parent()).
    Output
    -------
        f(var_val[0],.., var_val[-1])
    """
    phi = f.parent().hom(var_values, f.parent().base_ring())
    return phi(f)

def partial_eval_poly(f, var_value_pairs, infer_target_base_ring=False):
    """ Evaluate f at the given var value pairs. 

    Input
    -----
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_value_pairs : Dictionary with  variable:value   key-value-pairs, where value is in R.

    Output
    ----
        Geometrically restricts f to the smaller space, defined by the var_value_pairs.
        In particular, the result will lie in the polynomial ring generated by the variables not specified.
    
    Caveat
    ----
        It seems variables in sage are hashable and thus can be used as a dictionary key.

    TODO
    ----
        Infer the target ring type from the var_value_pairs. Else might fail, if first variable value is not specified.
    """
    # Build an "evaluation vector" which keeps the non-specified variables in place.
    R = f.parent()
    images = [var_value_pairs[x] if x in var_value_pairs.keys() else x for x in R.gens()]
    assert(len(images) >= 0)

    unspecified_vars = [x for x in R.gens() if x not in var_value_pairs.keys()]

    # Define the evaluation map. Note the * operator unpacks the variables into the polynomial ring constructor.
    # TODO: The target base_ring has to be infered from the var_value pairs!!
    target_base_ring = images[0].base_ring() if infer_target_base_ring else R.base_ring()
    phi = R.hom(images, target_base_ring if len(unspecified_vars) == 0 else target_base_ring[*unspecified_vars])

    return phi(f)


def shifted_lp_poly(R, p, mu):
    """ Constructs the shifted lp polynomial in the polynomial ring R. 

    Input
    ------
        R : PolynomialRing
        p : python int 
        mu : vector of size len(R.gens()) with entries in R.base_ring()  

    Caveat
    -------
        The convention we choose is that the interior of the lp ball is defined by 
        lp_poly >= 0.
    """
    return 1 - sum([(R.gens()[i] - mu[i])^(p) for i in range(0, len(R.gens()))])

def deformed_poly(f, defvarname):
    """ Introduces a new variable with the name defvarname, i.e. t, and returns f - t in the amended ring. 

    Input
    ------
        f : Polynomial 
        defvarname : string, indicating the new deformation variable

    Ouput
    ------
        f - t in the new ring f.parent()[t].
    """
    Rt = PolynomialRing(f.parent(), [defvarname])
    return f - Rt.gens()[0]
    
def deformed_product(fs, defvarname = "t"):
    """ Takes the product and deforms it by a parameter "defvarname".
    """

    # Check all are from the same parent ring.
    assert(all_from_same_parent_ring(fs))
    return deformed_poly(prod(fs), defvarname)
    

def get_1_dim_volume(fs, var_value_pairs, def_value, prec=NUM_BITS_PRECISION):
    """ In the setting of shifted lp-balls for p even, this return volume of the 
    deformed intersection of lp-balls ((Prod fs) - t) after intersection with the line defined by the 
    coordinate values for all but one coordinate.

    Input
    ------
        fs : List of polynomials in the same polynomial ring over QQ. 
        var_value_pairs : List of pairs (variable, value)
        def_value : Value, by which the product of the fs will be deformed.
        prec : Natural number, defining precision up to 2^(-prec).

    Output
    ------
        Length of the line defined by var_value_pairs intersecting with the deformed intersection of the {f >= 0}.

    Caveat:
    ------ 
        Assumes that the line actually intersects the deformed object and 
        that $t$ lies between 0 and the first critival value of the projection 
        from {(prod(fs) - t) = 0} to the t axis.

    TODO
    ------
    # TODO: Raise error when variable appears twice. 
    # TODO: Also need to make the caveat more precise.
    """
    # Deform the product to prod(fs) - t by the specified value for t.
    def_poly = eval_poly(deformed_product(fs), def_value)

    # Partially evaluate def_poly to land in a univariate polynomial ring.
    univariate_poly = partial_eval_poly(def_poly, var_value_pairs) 

    # HEURISTIC: The relevant line segment is bounded by the middle two real roots of univariate_poly,
    # see also the respective proposition in our paper. Will have evenly many roots in this setting.

    # Note: Also the real roots are only "real" with the given precision.

    real_roots = identify_real_roots(univariate_poly, prec, force_real=True)
    num_roots = len(real_roots)
    assert(num_roots % 2 == 0)

    # Sort the roots in increasing order:
    real_roots.sort()

    # The following difference will necesarily be positive.
    return real_roots[num_roots // 2] - real_roots[num_roots // 2 - 1]


# TODO: Instead of the below, simply use msolve! It does real root isolation.

def identify_real_roots(f, prec=NUM_BITS_PRECISION, force_real=False):
    """ For a univariate polynomial with rational coefficients, 
    it determines the roots which are real valued with the given precision.

    Strategy: Computes roots in QQbar. Discards roots with imaginary part larger than 2^(-prec) and 
                returns the remaining, still possibily represented to be complex valued, roots.
            
            TODO: Could also define the distance in terms of the value of f.

    Input
    ------
        f : Univariate polynomial over QQ.
        prec : precision in number of bits by which to discard imaginary parts.
        force_real : Boolean, whether the output should be forced to be algebraic real.
    """

    all_roots = f.roots(ring=QQbar)
    real_roots = [(root[0].real() if force_real else root[0])  for root in all_roots if abs(root[0].imag()) < 2^(-prec)]
    return real_roots

def branch_points(f, proj_var, field=QQbar, identify_real=False, prec=NUM_BITS_PRECISION):
    """ Computes all the branch points, i.e. points on V(f) over QQbar, unless other field provided, relative
        to the projection onto the proj_var-axis.

        The branch points are the solutions to the ideal 
            I = (f) + ( diff(f, x_i) | x_i != proj_var).
        
        The solutions are computed over QQbar. 
        Note: If the coefficients of f are in QQ, then all solutions
        are in QQbar [REF]
    
    Input
    ------
        f : Multivariate polynomial over QQ
        proj_var : A variable out of f.parent().gens()

    Output
    ------
        A representation of the branchpoints.
    """
    R = f.parent()

    I = R.ideal([f] + [diff(f, x) for x in R.gens() if not (x == proj_var)])

    # Now solve the ideal, assuming it is just a collection of points.
    # TODO: Can essentially remove the the assertion, as it will be necessarily true. Why?
    assert(I.dimension() == 0)

    variety = I.variety(field)

    if identify_real:
        # TODO: Later test, if abs does slow down. Can just replace by "and" of the two comparisons then.
        # TODO: Perhaps solving over AlgReal might be better?
        return [point for point in variety if all([abs(point[key].imag()) < 2^(-prec) for key in point.keys()])]
    else:
        return variety

def project_deformed_intersection(fs, def_value, proj_var, var_value_pairs, prec=NUM_BITS_PRECISION):
    """ Computes the minimum and maximum value that proj_var takes on the deformed volume_intersection,
    after restricting to the chosen var_value_pairs.

    Input
    -------
        fs              : A list of multivariate polynomials
        def_value       : In QQ, value by which the product is deformed.
        proj_var        : The variable, such that we project onto the proj_var-axis.
        var_value_pairs : The values already restricted to.

    Output
    -------
        An interval representing the [min, max] value of proj_var on the deformed intersection.
    
        This can be done in terms of computing real branch_points lieing on the boundary 
        of the deformed intersection and then projecting onto proj_var.

    Caveat
    -------
        The semi-algebraic set "intersection" refers to the intersection of {f_i >= 0}.
        The "deformed semi-algebraic set" refers to the connected component of {prod(f) - t >= 0}
        that lies within the "intersection".


    TODO
    -----
        - Check how fast this is in practice. And if there is a better way with numerical optimization 
            techniques, given that our set of interest is convex [proof].   
    """
    
    # Compute all "real" branch points 
    fdef = partial_eval_poly(eval_poly(deformed_product(fs), [def_value]), var_value_pairs)
    real_branch_points = branch_points(fdef, proj_var, identify_real=True, prec=prec)       # TODO Issue: Already for small example, solving over QQbar takes for ever!!!
    # Now identify the branchpoints satisfying f >= 0 for all f in fs:
    inside_branch_points = [point for point in real_branch_points if all([partial_eval_poly(f, to_real(point), infer_target_ring=True) >=0 for f in fs ])]
    
    # Now return only the proj_var values 
    # TODO: Split this actually into two functions, so that one can utitilize the computed branch_points if in interest.
    return [{proj_var:point[proj_var]} for point in inside_branch_points]


def get_picard_fuchs(fs, deform_value, var_value_pairs, proj_var, strategy=None):
    """ Computes the Picard Fuchs operator for 
    Vol(proj_var) = Vol( p^{-1}(proj_var) \cap {fs \geq 0 forall s} \cap slice(var_value_pairs)).

    Input
    ------
    fs              : Polynomials defining semi-alg set (by fs >= 0)
    deform_value    : Value in QQ, by which to smooth prod(fs).
    var_value_pairs : defining slice to restrict to.

    Output
    ------
    P : Picard Fuchs operator, in WeylAlgebra D_{proj_var}

    TODO
    -----
    Make the procedure by which to compute the intersection ideal more informed.
    """

    # Construct the integrand
    A = construct_integrand(fs, deform_value, var_value_pairs, proj_var)
    
    W = rational_weyl_algebra(A.parent().ring())

    annA = W.ideal([A*D-D(A) for D in W.gens()]) # construct the annihilating ideal

    # To be precise, below we simply construct some subset of the integration ideal, 
    # but it suffices to be non-empty.
    intIdeal = creative_telescoping(annA, proj_var)

    return intIdeal.gens()[0]

def construct_integrand(fs, deform_value, var_value_pairs, proj_var):
    """ By standard considerations, see for example our paper, the function 
    vol(proj_var) can be expressed as period of a rational function A. 
    We construct this function rational function here, considering  closely the order of indeterminate variables
    and the proj var.

    Input
    ------
    See get_picard_fuchs()

    Output
    -----
    A : Element of a FractionField. (TODO: Specify more clearly the variables.)
    """

 
    fdef = partial_eval_poly(eval_poly(deformed_product(fs), [deform_value]), var_value_pairs)
    
    # Multiply out the denominators and change to integer ring:
    fdef_ZZ = fdef.numerator().change_ring(ZZ)
    proj_var_ZZ = fdef_ZZ.parent()(proj_var)

    prim_var = [var for var in fdef_ZZ.parent().gens() if not var == proj_var_ZZ][0] # TODO: Here taking the first, should make this more strategic here.
    
    sgn = (-1)^0 # TODO: Should depend on the choice of prim_var, to account for ordering.

    A = sgn * diff(fdef_ZZ, prim_var) * prim_var / fdef_ZZ # Automatically constructs the fraction field.

    return A


def get_picard_fuchs_t(fs, strategy=None):
    """ Computes the Picard Fuchs operator for 
    Vol(t) = Vol( prod(fs) - t >= 0) \cap {fs \geq 0 forall s} 

    Input
    ------
    fs              : Polynomials defining semi-alg set (by fs >= 0)

    Output
    ------
    P : Picard Fuchs operator, in WeylAlgebra D_{t}

    TODO
    -----
    Make the procedure by which to compute the intersection ideal more informed.
    """

    deform_var_name = "t"

    # Construct the integrand, note that here this is over the ring QQ[x..., t], rather than QQ[x..][t]
    At = construct_integrand_t(fs, deform_var_name, strategy)
    
    Wt = rational_weyl_algebra(At.parent().ring())

    annAt = Wt.ideal([At*D-D(At) for D in Wt.gens()]) # construct the annihilating ideal

    # To be precise, below we simply construct some subset of the integration ideal, 
    # but it suffices to be non-empty.
    intIdeal_t = creative_telescoping(annAt, At.parent().ring()(deform_var_name))

    return intIdeal_t.gens()[0]


def construct_integrand_t(fs, def_var_name, strategy=None):
    """ See construct_integrand(). Constructs the picard fuchs operator for the deformed slice
    vol(t) = vol({prod(fs)-t >= 0} \cap {fs >= 0})

    Input
    -----
        See get_picard_fuchs_t()
    """

    ft = deformed_product(fs, def_var_name)

    ft_flattened = ft.parent().flattening_morphism()(ft) # flatten the ring.

    # Multiply out the denominators and change to integer ring:
    ft_flattened_ZZ = ft_flattened.numerator().change_ring(ZZ)


    proj_var_ZZ = ft_flattened_ZZ.parent()(def_var_name)

    prim_var = [var for var in ft_flattened_ZZ.parent().gens() if not var == proj_var_ZZ][0] # TODO: Here taking the first, should make this more strategic here.
    
    sgn = (-1)^0 # TODO: Should depend on the choice of prim_var, to account for ordering. (Or maybe it doesn't matter? Either does annihilate it.)

    At = sgn * diff(ft_flattened_ZZ, prim_var) * prim_var / ft_flattened_ZZ # Automatically constructs the fraction field.

    return At

def rational_weyl_algebra(polyRing):
    """ Constructs the rational Weyl algebra for a specified polynomial ring.
    """
    fracField = polyRing.fraction_field()

    return OreAlgebra(fracField, *[("D" + str(var), {}, {str(var) : 1}) for var in polyRing.gens()])

def creative_telescoping(I, proj_var, strategy=None):
    """ For an ideal in the rational Weyl algebra W, it carries out creative telescoping
    sequentially to eliminate all but proj_var.

    The result is an ideal contained in:     (I + dx_1 * D + ...+ dx_n *D) \cap D_x0
    (In this example we assume x0 to be the proj_var)

    Output
    ------
    ct_ : Returns a list of of univariate differential operators of length 1 (!).

    TODO
    ------
    - Should extend this, so that at least temporarily we store / output for debuginfo the certificates, too.
    - Should include some basic strategy.
    """
    W = I.ring()
    ct_system = list(I.gens())
    for Dvar in [Dvar for Dvar in W.gens() if not Dvar == W("D"+str(proj_var))]:
        ct_ideal = ct_system[0].parent().ideal(ct_system)
        ct_system = ct_ideal.ct(Dvar, certificates=False)
    return ct_system[0].parent().ideal(ct_system)

# def volume_intersection(p, translation_vectors, precis): #assume that dim > 1, p>1 even, translation vectors give non-empty intersection!
#     """ Computes the volume of the intersection of L_p balls shifted by translation_vectors in RR^dim. 

#     Input
#     -----
#     p : integer, assumed even.
#     translation_vectors : list of vectors in QQ^dim
#     precis : integer precision digits

#     Output
#     ------
#     The volume of the intersection of the translated L_p balls as a fixed precision real number.

#     Example
#     -----
    
#     p = 4
#     translation_vectors = [(0,0), (1,0)]
    
#     vol = volume_intersection(dim,p,translation_vectors)  # 1.71448285904485523624162985240570841916093...

#     """
#     dim = len(translation_vectors[0])
#     k = len(translation_vectors)
#     Rt = PolynomialRing(ZZ, 'x', dim+1) # note that xdim+1 is t, i.e. Rt.gens()[-1] or Rt.gens()[xdim]
#     Ft = Rt.fraction_field()    
#     Wt = OreAlgebra(Ft, *[("Dx" + str(i), {}, {"x" + str(i) : 1}) for i in range(0, dim+1, 1)])
    
#     # create complex ring for creative telescoping and real ring for precision 
#     # 

#     # make the polynomial ft = f1*...*fk - t
#     ft = Rt(1)
#     for mu in translation_vectors: 
#         ft = ft * shifted_lp_poly(Rt, p, mu)

#     ft = ft - Rt.gens()[-1]

#     At = Ft(y*ft.derivative(Rt.gens()[0])/ft) # differentiat by x0. this means we always telescope wrt x0 first.  
#     annt = Wt.ideal([At*D-D(At) for D in Wt.gens()])

#     # telescope to get Picard-Fuchs in xdim+1  (i.e. eliminate all variables but the last one)
#     ct0 = annt.ct(Wt.gens()[0], certificates=False)
#     for i in range(1, dim): 
#         ct0 = ct0[0].parent().ideal(ct0).ct(Wt.gens()[i], certificates=False)
#     order0 = ct0[0].order()

#     # CHOOSE SLICES 
#     max0 = QQ[Rt.gens()[dim+1]](ct0[0].leading_coefficient()).roots(RB, multiplicities=False) #what is RB
#     # TODO : Find the t0 smallest positive, real critical value and choose order0 many points between 0 and  t0
#     # L0 = [...] values of x0 for slices! 
#     # Check if L0 is a good set - it should give an invertible matrix. before or after computing volumes? 

#     # now we compute order0 volumes of x[dim]-slices. 
#     x0_volumes = []
#     for i in range(0,order0):
#         # smooth algorithm begins here
#         j=0
#         # f = ft(R.gens()[dim] = L[i]) #evaluate it before calling!!
#         something = smooth_volume(j,L[i],ft,dim,RB)
#         x0_volumes.append(something)
#     # analytically continue to get volume at x[dim] = 0
#     return final_volume


# def smooth_volume(j, point, f1, dim, RB):
#     R = PolynomialRing(ZZ, dim-j, 'x') #Note that now, x0 = x, x1 = y, ...
#     F = R.fraction_field()    
#     W = OreAlgebra(F, *[("Dx" + str(i), {}, {"x" + str(i) : 1}) for i in range(0, dim-j, 1)])
#     # TODO
#     # f = None
#     f = F(f1(R.gens()[dim - j] = QQ(point))) #can't evaluate here!!
#     A = F(y*f.derivative(R.gens()[0])/f)
#     ann = W.ideal([A*D-D(A) for D in W.gens()])
#     ct = ann.ct(W.gens()[0], certificates=False)
#     if j == dim-2:
#         # do nothing
#         pass
#     else:
#         for k in range(1,dim-j-1):
#             ct = ct[0].parent().ideal(ct).ct(W.gens()[k], certificates=False)
#     ord = ct[0].order()
#     L = QQ[R.gens()[dim-j-1]](ct[0].leading_coefficient()).roots(RB, multiplicities=False)
#     # TODO kick out unwanted critical points
#     initial_conditions = []
#     slice_values = #find ord+1 slices
#     for i in ord+1:
#         if j == dim-2: 
#             # TODO actually compute a volume 
#             # here we must use our conjecture.
#             f = f(R.gens()[dim - j] = slice_values[i])
#             # we select the middle two points
#             roots = (QQ[R.gens()[0]](f)).roots(RB, multiplicities=False)
#             len_roots = len(roots) + 1 # this should be even
#             slice_vol = roots[len_roots/2] - roots[len_roots/2 - 1]
#         else:
#             slice_vol = smooth_volume(j+1, slice_values[i], f, dim, RB)
#             initial_conditions.append(slice_vol)

#     # TODO use the initial conditions to compute the volume of this slice. 
#     return volume        
    