"""
Commonly used methods within the volumes package.
"""

# Sage Imports

from sage.all import prod
from sage.all import PolynomialRing
from sage.all import QQbar


# Classical assertions:
def all_from_same_parent_ring(fs):
    return all([f.parent() == fs[0].parent() for f in fs])

# Useful methods:

def eval_poly(f, var_values):
    """ Evaluates a polynomial at a specified value of the variables. 
    This method is a wrapper for applying to f the ring map to the base ring, 
    which sends the variables to the specified values.

    Input
    -------
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_values : a vector of length len(f.parent().gens()) with values in base_ring(f.parent()).
    Output
    -------
        f(var_val[0],.., var_val[-1])
    """
    phi = f.parent().hom(var_values, f.parent().base_ring())
    return phi(f)

def partial_eval_poly(f, var_value_pairs, infer_target_base_ring=False):
    """ Evaluate f at the given var value pairs. 

    Input
    -----
        f : Polynomial in f.parent() = R[x1,..,xn] (where R denotes the basering)
        var_value_pairs : Dictionary with  variable:value   key-value-pairs, where value is in R.

    Output
    ----
        Geometrically restricts f to the smaller space, defined by the var_value_pairs.
        In particular, the result will lie in the polynomial ring generated by the variables not specified.
    
    Caveat
    ----
        It seems variables in sage are hashable and thus can be used as a dictionary key.

    TODO
    ----
        Infer the target ring type from the var_value_pairs. Else might fail, if first variable value is not specified.
    """
    # Build an "evaluation vector" which keeps the non-specified variables in place.
    R = f.parent()
    images = [var_value_pairs[x] if x in var_value_pairs.keys() else x for x in R.gens()]
    assert(len(images) >= 0)

    unspecified_vars = [x for x in R.gens() if x not in var_value_pairs.keys()]

    # Define the evaluation map. Note the * operator unpacks the variables into the polynomial ring constructor.
    # TODO: The target base_ring has to be infered from the var_value pairs!!
    target_base_ring = images[0].base_ring() if infer_target_base_ring else R.base_ring()
    phi = R.hom(images, target_base_ring if len(unspecified_vars) == 0 else target_base_ring[*unspecified_vars])

    return phi(f)


def shifted_lp_poly(R, p, mu):
    """ Constructs the shifted lp polynomial in the polynomial ring R. 

    Input
    ------
        R : PolynomialRing
        p : python int 
        mu : vector of size len(R.gens()) with entries in R.base_ring()  

    Caveat
    -------
        The convention we choose is that the interior of the lp ball is defined by 
        lp_poly >= 0.
    """
    return 1 - sum([(R.gens()[i] - mu[i])**(p) for i in range(0, len(R.gens()))])

def deformed_poly(f, defvarname):
    """ Introduces a new variable with the name defvarname, i.e. t, and returns f - t in the amended ring. 

    Input
    ------
        f : Polynomial 
        defvarname : string, indicating the new deformation variable

    Ouput
    ------
        f - t in the new ring f.parent()[t].
    """
    Rt = PolynomialRing(f.parent(), [defvarname])
    return f - Rt.gens()[0]
    
def deformed_product(fs, defvarname = "t"):
    """ Takes the product and deforms it by a parameter "defvarname".
    """

    # Check all are from the same parent ring.
    assert(all_from_same_parent_ring(fs))
    return deformed_poly(prod(fs), defvarname)

